### ISSUE TITLE
Implement New UI design

### ISSUE THREAD

**Issue by heyfirst** [firstziiz/luna-frontend#4]
As a PO, I want to change our user interface in my project so that our user interface have more clean and beautiful.

**Exit Criteria**
- [x] Learning UI from https://www.interseller.io
- [x] Implement Clean UI from figma

**Additional Note**

**Related ticket(s):**

---

**Comment by penthaizza** [comment]
- Update New TopicPage UI 
- Update New Navbar

**Comment by penthaizza** [comment]
- Update New TopicPage UI 
- Update New TaskListPage UI
- Update New Navbar
